export type ReservedWordType = 'PIC' | 'PICTURE' | 'VALUE' | 'VALUES' | 'OCCURS' | 'TIMES' |
    'DEPENDING ON' | 'TO' | 'INDEXED BY' | 'BINARY' | 'REDEFINES' | 'USAGE' | 'COMP' |
    'COMPUTATIONAL' | 'COMP-1' | 'COMPUTATIONAL-1' | 'COMP-2' | 'COMPUTATIONAL-2';
